name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version in 0.0.0 format'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci 
      - run: npm run package -m "Release ${{ github.event.inputs.version }}" ${{ github.event.inputs.version }}
      - run: git push --follow-tags
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          files: "*.vsix"
          generate_release_notes: true