name: Schedule release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version in 0.0.0 format'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    env:
      VERSION: v${{ github.event.inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm version -m "Update version to $VERSION" ${{ github.event.inputs.version }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Create release $VERSION"
          branch: release/$VERSION
          delete-branch: true
          title: "Create release $VERSION"
          body: "Updates version to $VERSION"
          labels: Release

